### ISSUE TITLE
Support for tellstick Net v2?

### ISSUE THREAD

**Issue by bialad** [molobrakos/tellsticknet#13]
I've made a question in the hass community [here](https://community.home-assistant.io/t/tellstick-net-v2-with-hass-io/71730), but no replies. Trying here instead.

When I run "tellsticknet discover" it shows the following:

```
18-10-13 07:11.17  INFO (MainThread) [tellsticknet.discovery] Discovering tellstick devices ...
18-10-13 07:11.17  INFO (MainThread) [tellsticknet.discovery] Malformed reply
```

I have the [Tellstick Net v2](https://www.netonnet.se/art/hem-hushall/smarta-hem/hemautomatisering/telldus-tellstick-net-eu-v2/235130.9436/), and I'm wondering if that model is supported?

I'm using the tellsticklive component in hass now, and it runs like clockwork. But, I'd like to keep my device on the local network.

**Comment by molobrakos** [comment]
You'll have to debug and see what is returned by your device here: https://github.com/molobrakos/tellsticknet/blob/master/tellsticknet/discovery.py

**Comment by bialad** [comment]
This is what is returned:

```
INFO (MainThread) [tellsticknet.discovery] ['TellstickNetV2', 'ACCA5401E1FE', 'J7EUU92NGQ', '1.1.0', '078c2192-54ec-42a5-acd7-447496f505ab']
```

**Comment by molobrakos** [comment]
Please test if https://github.com/molobrakos/tellsticknet/commit/a9e73c29d0cf3a2d322379283e266ded596b9a63 solves your issue. Since I don't have access to the device I unfortunately can not debug it myself.

**Comment by bialad** [comment]
It did! But now these is instead the problem of reading the sensor values, I guess they change to format?

```
[tellsticknet.protocol] failed to decode packet, skipping: b'7:RawDatah8:protocolA:fineoffset2:idi98s6:valueslh5:scalei0s4:typei1s5:value4:16.6ss5:modelB:temperature4:datai4980A6FFBBs5:class6:sensors'
```

**Comment by molobrakos** [comment]
Couldn't resist, added it now. :-)

**Comment by bialad** [comment]
It works! Great job doing this without a device available. :)

**Comment by bialad** [comment]
I've now started working on sending packets to a mosquitto broker, which in principle seems to work but the packages are not formatted correctly. Maybe you can take a look.

I receive the following from my gateway:

```
Got packet {'protocol': 'fineoffset', 'id': 151, 'values': [{'scale': 0, 'type': 1, 'value': '21.1'}, {'scale': 0, 'type': 2, 'value': 61}], 'model': 'temperaturehumidity', 'class': 'sensor', 'sensorId': 151, 'data': [{'name': 'humidity', 'value': 61}, {'name': 'temp', 'value': 21.1}], 'lastUpdated': 1541602302}
```

But it then crashes on line 307 of mqtt.py, `if item['name'] == self.sensor)`. If I remove that line, it passes but what's received in the broker is not what I expect.

```
{"name": "Inne None", "state_topic": "tellsticknet/acca5401e1fe/sensor/inne none/state", "retain": true, "availability_topic": "tellsticknet/acca5401e1fe/sensor/inne none/avail", "payload_available": "online", "payload_not_available": "offline", "command_topic": "tellsticknet/acca5401e1fe/sensor/inne none/set", "unit_of_measurement": null}
```

Looking at the code, I except the value property to be sent to the broker. Is this also a format mismatch?

**Comment by bialad** [comment]
Sorry, forgot to include the config.

```
name: Inne  # name unique across sensors
class: sensor  # optional
protocol: fineoffset
model: temperaturehumidity
sensorId: 151
```

**Comment by molobrakos** [comment]
Please re-test with latest commit and see if it solves this problem for you.

**Comment by molobrakos** [comment]
No response... please test and re-open if it still is not solved
