### ISSUE TITLE
Archtec codeswitch does not work?

### ISSUE THREAD

**Issue by Gohper** [molobrakos/tellsticknet#20]
Hi,
tried to turn on an codeswitch device, the log says it is sending selflearning.

Ideas?

**Comment by Gohper** [comment]
For other protocols, what about this code, https://github.com/telldus/telldus/blob/master/telldus-core/service/ , possible/useful to convert to python?
I the your tellsticknet, it seems to do all that is implemented very good!
Oh sending message on the phone, my fingers are to big!

**Comment by molobrakos** [comment]
Please feel free to contribute! I'll accept any bug fixes or additions with support for more protocols.

**Comment by Gohper** [comment]
Allmost there for the Arctech codeswitch...
I assume that the new encoding call is top be in the archtech .py line 27.
`    if model == "codeswitch":
        return encode_codeswitch(house, unit, method)
    elif method == const.TURNON and model == "selflearning-dimmer":
        method, param = const.DIM, 255
    elif method == const.DIM and int(param) == 0:
        method = const.TURNOFF`

Sorry for the code tag layout....

And I also assume that def encode(model, house, unit, method, param, **kwargs): returns bytes.
Is this correct?

First I thought that, in the tellstick net, built in support for self learning was used, but it looks like this is encoded in the protocol.
Hopefully I will test this during the weekend. :o)

**Comment by molobrakos** [comment]
"Gives error on all targets..." is insufficient information, sorry.

**Comment by Gohper** [comment]
Ok, I have not had the time to dig deeper into this.
I will post a log when I have the time.
