### ISSUE TITLE
binary_sensor no longer publishes on configuration topic

### ISSUE THREAD

**Issue by odtgit** [molobrakos/tellsticknet#22]
Thanks for the recent updates, really appreciate it! Anyway noticed that HA was not picking up the binary sensor topics any longer automatically and this seems to be due to the configuration topic not being pubished for binary_sensor type - still works fine for switches.

I work around it right now by using these state topic directly as custom MQTT sensors witht the new topic path - this still works fine.

**Comment by molobrakos** [comment]
Thanks for reporting, I will have a look! (sometimes I forget there are other users than myself). I had to make a fix for invalid configuration keys getting published to Home Assistant for binary sensors.

**Comment by molobrakos** [comment]
Commands/switches are configured automatically in Home Assistant upon startup, but sensors will be discovered only when the first sensor reading is available:
https://github.com/molobrakos/tellsticknet/blob/master/tellsticknet/mqtt.py#L552-L560
I guess this could be an option, but it doesn't make much sense to configure/add sensors to HA with no data available.

**Comment by molobrakos** [comment]
Fixed: https://github.com/molobrakos/tellsticknet/commit/ac9b4f9a57a461614929ef4b29c8c089328b84b1
