### ISSUE TITLE
Hi. Is your plugin compatible with the new "TellStick ZNet Lite v2"

### ISSUE THREAD

**Issue by ovelie** [molobrakos/tellsticknet#25]

**Comment by ovelie** [comment]
if I try, I get:

19-09-23 10:32.29  INFO (MainThread) [tellsticknet.discovery] Discovering tellstick devices ...
19-09-23 10:32.29  INFO (MainThread) [tellsticknet.mqtt] Connecting
19-09-23 10:32.29  INFO (MainThread) [transitions.core] Exited state new
19-09-23 10:32.29  INFO (MainThread) [transitions.core] Entered state connected
19-09-23 10:32.29  INFO (MainThread) [tellsticknet.mqtt] Connected to MQTT server
19-09-23 10:32.34  INFO (MainThread) [transitions.core] Exited state connected
19-09-23 10:32.34  INFO (MainThread) [transitions.core] Entered state disconnected
No tellstick device found

**Comment by fredrike** [comment]
I didn't know that TellStick Znet Lite v2 is new (released in Oct. 2016) [312692_ProductSheet_161021_SV.pdf](https://proove1.app.box.com/embed/s/ahj73hom7yk533ijuty142ojimzk7lt5/file/98763566504)..

I suggest that you install and run the native mqtt plugin directly on your Znet Lite https://github.com/quazzie/tellstick-plugin-mqtt-hass
